# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->

Identifying, accessing, curating, and sharing datasets can be a huge time sink for data science educators, which often (understandably) results in the continued use of stale or poorly documented datasets that lack real-world relevance (see: `iris`, `mtcars`, etc.). These datasets can be unintuitive (e.g. what is a "Sepal width?") and uninspiring for learners who might struggle to connect course examples (e.g. assessing Titanic survival) with modern challenges, questions, or implications they care about. Thus, there is a need for modern, approachable, easy-to-access datasets that (1) spare data science teachers from spending time and energy on the "data hunt", (2) provide students with opportunities to learn and work with data they are more likely to care about, and (3) can foster discussions about current real-world questions. 

Valuable data packages have been developed by R community members. Many provide easier access to large datasets and databases (e.g. the [`wcfish`](https://github.com/cfree14/wcfish) R package by Free et al., which contains data from US West Coast fisheries). While similar packages are excellent resources for researchers, they are often not specifically designed with educators in mind (i.e., the data are often raw, and would require time-consuming exploration and curation for use in introductory data science courses). Recently, R packages providing datasets curated for education have been developed. For example, the [`palmerpenguins`](https://allisonhorst.github.io/palmerpenguins/) by Horst, Hill and Gorman (2020), contains a dataset **penguins** that was specifically selected and curated for characteristics amenable for teaching introductory data science and statistics courses, including: intuitive and charismatic subjects (penguins) and variables (e.g. flipper length, body mass), manageable size (344 observations), linear relationships and multivariate normality. The appetite for data packages designed for data science education is clear from `palmerpenguins`' widespread use in educational materials, courses, and examples. 

While `pamerpenguins` filled a specific need in the R community (a modern alternative to `iris`), there remains a need for similarly interesting, curated modern datasets for data science education that span a greater range of topics, sizes, variable types, and data structures. The `lterdatasampler` - which already contains 8 data samples - can be such a resource for instructors who want to teach using real-world environmental datasets from the US Long Term Ecological Research Network.

Free CM, Vargas Poulsen C, Bellquist LF, Wassermann SN, Oken KL (2022) The CALFISH database: a century of California’s non-confidential fisheries landings and participation data. Ecological Informatics 69: 101599. https://doi.org/10.1016/j.ecoinf.2022.101599

Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. https://allisonhorst.github.io/palmerpenguins/. doi: 10.5281/zenodo.3960218.

