# The proposal
<!--
This is where the proposal should be outlined. 
-->

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

Identifying, curating, and making available appropriate datasets for use in data science education is a tedious and time consuming task for teachers. The widespread adoption of the recently published [`palmerpenguins`](https://allisonhorst.github.io/palmerpenguins/) R package highlights the R community's appetite for modern, easy-to-access datasets. We are developing the [`lterdatasampler`](https://lter.github.io/lterdatasampler/) R package to provide additional refreshing, curated and approachable environmental data samples from the 28 sites that make up the [US Long Term Ecological Research Network](https://lternet.edu/) (LTER). Data samples are selected for their usefulness in teaching introductory statistics and data science in R. Overall, we aim to create a resource that supports teachers who want to exchange stale and/or poorly documented datasets (e.g. `cars`) with more relevant, engaging and documented options. 

We recently publicized our first version of the package, which contains 8 data samples, to solicit feedback from the R community. Based on the strong engagement and positive reaction, we are inspired to move forward with our plan to grow the package to include one data sample from each of the 28 LTER network sites. We seek funding to support our continued work on the [`lterdatasampler`](https://lter.github.io/lterdatasampler/) R package, which we believe will be a widely valuable resource for teachers and learners who want to modernize their course materials with real-world environmental datasets. 

## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

The outcome of this product will be the expanded [`lterdatasampler`](https://lter.github.io/lterdatasampler/) R package, which we plan to increase from the current 8 data samples to a total 28 data samples (one from each of the 28 LTER Network sites). 

The package follows standard R package infrastructure (see the project repo: https://github.com/lter/lterdatasampler) and contents are fully reproducible from raw data (hosted at the Environmental Data Initiative, [EDI](https://environmentaldatainitiative.org/)) through to curated samples using the [`metajam`](https://github.com/NCEAS/metajam) package. 

The `lterdatasampler` [website](https://lter.github.io/lterdatasampler/), made with [`pkgdown`](https://pkgdown.r-lib.org/), provides standard information about the datasets, along with vignettes, photos, "fun facts," and other information shared by LTER researchers that can help educators bring the data to life. In addition, the homepage features a ["Which dataset should I use?"](https://lter.github.io/lterdatasampler/#which-data-sample-should-i-use) table that directs visitors to data samples that are useful for teaching and practicing common methods in introductory statistics and data science classes. For example, the instructors teaching simple linear regression can quickly learn that the `pie_crabs` (fiddler crab body size), `ntl_icecover` (lake ice cover duration), and `hbr_maples` (maple tree seedling growth) datasets provide opportunities to explore linear relationships. We hope this feature makes data sample selection even quicker for teachers and learners. 

As mentioned above, we also provide the code we developed to clean and simplify the original data set into the teaching curated data sample. This code provides and all the necessary information to download the original data and metadata. This allow the users to go from the simplified version of the data used in the teaching example to the more complex one that was used for research purposes. This workflow also promotes reproducible science and data management best practices by providing metadata and direct access to a data repository hosting the data. These tools rely on [DataONE](https://www.dataone.org/)'s cyberinfrastructures and can be applied to other data repositories.

To select the right teaching dataset, we take into account data characteristics using selection criteria described in Horst et al. (in press) including:

- Interesting and approachable topic and/or subjects
- Easy to understand data set (intuitive variables)
- Can be simplified, while still presenting interesting patterns or relationships useful for teaching in introductory data science and statistics courses

Our more comprehensive vision is to offer a suite of data samples that:

- Cover a large variety of data science techniques and statistical concepts, including data wrangling, analysis, and communication (e.g. data visualization)
- Feature a variety of data types (e.g. tabular, spatial, text, time series, and more)
- Span a range of topics (e.g. natural sciences, social sciences, ecology, climate science, political science, etc.)

With these characteristics in mind - both within individual data samples, and across the package - identifying, exploring and developing suitable datasets requires substantial trial and error. While the current package hosts 8 complete data samples, many more that have been explored. We are convinced that the LTER network has the data richness required for this project, and plan to use our connections with the LTER community to find valuable teaching data sets that satisfy the characteristics we have described.




