# Requirements

```{=html}
<!-- 
An idea of what is required to make the project actually happen
-->
```
## People

Proposers (Horst and Brun) are the primary authors of the `lterdatasampler` R package, and are currently the sole developers. Non-financial support is provided by the LTER Network Office, LTER Education Committee, LTER researchers and site Information Managers.

## Processes

```{=html}
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->
```
We have established a system for communicating with LTER Information Managers, leadership, and researchers to gather feedback on package datasets and vignettes.

Still needed are:

-   A more thorough "How to contribute" guide, so that we can incorporate (or link to) external contributor's examples as the data samples get used in different and interesting ways
-   Feedback from the R community (particularly educators and learners who are using the `lterdatasampler` package), which we intend to gather through an informal survey (likely a Google form)

## Tools & Tech

```{=html}
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->
```
We will continue to build out `lterdatasampler` using the same tools and reproducible workflow that we have established in the [existing version](https://github.com/lter/lterdatasampler) of the package.

No additional tools or tech are expected.

## Funding

```{=html}
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE



-->
```
Total funding requested: \$19,745

Budget:

-   \$10,395: Allocated to Horst, as compensation for time spent expanding the `lterdatasampler` R package as detailed below
-   \$9,350: Allocated to Brun, as compensation for time spent expanding the `lterdatasampler` R package as detailed below

We justify the requested amount based on an approximate total time spent on each datasample of 12 hours (includes finding, curating, adding to package, documenting, creating a vignette, reaching out to and getting feedback from LTER scientists, etc.). The current package contains data samples from 8 (of 28) LTER sites. With 20 additional data samples needed to complete `lterdatasampler`, we estimate the following time commitments to complete the package:

| Item                                                            | Expected Hours | Lead         | Funding requested |
|--------------------------------|-----------------|-------------|----------|
| Data sample development                                         | 256            | Horst & Brun | \$14,080          |
| Artwork                                                         | 20             | Horst        | \$1,100           |
| Community Survey Development                                    | 15             | Horst        | \$825             |
| Community Survey Analysis and Reporting                         | 16             | Brun         | \$880             |
| "How to contribute" guide development                           | 32             | Horst & Brun | \$1,760           |
| Outreach (blog, twitter threats, community presentations, etc.) | 20             | Horst & Brun | \$1,100           |
| **Total**                                                       | 359            |              | ***\$19,745***    |

## Summary

```{=html}
<!--
A summary of the requirements that contextualises the costs
-->
```
We request the funding above (\$19,745 total) to directly support developers Horst (\$10,395) and Brun (\$9,350) as salary for their time and effort spent expanding the `lterdatasampler` package for R educators and learners.
